#1 안드로이드 초기 세팅
Nexters/winepick-android pull request #3
Opened 2021-01-27 19:14 UTC by riflockle7

#1

2021-01-30 05:50 UTC, riflockle7 commented
일단 기본적인 화면 작업 기능만 올려둔 상태여서 (MVVM, DataBinding) 
아직 코루틴이라거나 Rx 에서 필요한 내용들은 넣지 않은 상태입니다. 일부 내용들은 리뷰하면서 넣어볼까 생각했어서..! 

현재 이걸로 MVVM, DataBinding 확인해보시고 추가하고 싶은 내용이나 잘못 작성되어 있거나 하는 내용 말씀해주시면 될 것 같고
위에서 언급했던 내용 (Rx 등) 에 대해서도 이야기 되면 좋을 것 같아요

2021-01-30 05:54 UTC, riflockle7 commented
slack PR 메시지 테스트

2021-01-30 06:00 UTC, yunakim2 reviewed
주석까지 모두 완벽해서 사실 코드에 관한 리뷰를 해드릴 게 없네요,, 너무 고생하셨어요 👍🏻

2021-01-30 06:01 UTC, riflockle7 commented
코드리뷰 관련 3가지 방법 : https://www.notion.so/406b5cac78874e8da23a034ac0d7992a

2021-01-30 06:09 UTC, riflockle7dummy requested changes
Request changes 의 예

2021-01-30 06:09 UTC, riflockle7dummy commented on app/src/main/java/kr/co/nexters/winepick/WinePickApplication.kt
> + * @author ricky
@author 을 빼거나 각 파일에 추가하거나 선택해야 될 것 같습니다.

2021-01-30 06:11 UTC, riflockle7 reviewed
comment 의 예

2021-01-30 06:11 UTC, riflockle7 commented on app/src/main/java/kr/co/nexters/winepick/WinePickApplication.kt
> + * @author ricky
이 파일에 이름이 빠지거나 아니면 새로 규칙을 만들거나 해야할 것 같아요

2021-01-30 06:11 UTC, riflockle7 commented on app/src/main/java/kr/co/nexters/winepick/example/java/normal/JavaDefaultFragment.java
> +        binding.tvTitle.setText("자바 프레그먼트 테스트");
문자열을 `하드코딩`이 아닌 다른 방식으로 하면 어떨까요?

2021-02-08 06:10 UTC, ricky-buzzni approved these changes

2021-02-08 06:11 UTC, merged